News detail
wolox-training/rm-android pull request #12
Opened 2019-08-05 18:22 UTC by rickwolox

### Summary
New Detail feature. This branch includes new's detail, like or dislike new, image fullscreen when clicked. Also the previous list is updated when some news are updated.

### Screenshot
<img src="https://user-images.githubusercontent.com/53051075/62485697-ceda4f80-b793-11e9-97ad-78126b2e2536.png" width="300" >  <img src="https://user-images.githubusercontent.com/53051075/62485698-cf72e600-b793-11e9-94a7-fdc7859f5895.png" width="300" >

### Trello Card
https://trello.com/c/IMs90Zhf/8-u6-frontend-and-backend-news-detail

2019-08-05 18:46 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/newdetail/NewDetailFragment.kt
> +        if (handleArguments(arguments)) {
override handleArguments to check if it's null or not

2019-08-05 18:47 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/newdetail/fullscreen/FullScreenPictureDialog.kt
> +        if (handleArguments(arguments)) {
Same as above

2019-08-05 18:48 UTC, lmiotti commented on app/src/main/res/layout/fragment_new_detail.xml
> +
Remove empty line

2019-08-05 18:48 UTC, lmiotti commented on app/src/main/res/layout/fragment_new_detail.xml
> +    </androidx.core.widget.NestedScrollView>
Add empty line above and below

2019-08-05 18:50 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/model/New.kt
> +    @SerializedName("likes") var likes: List<Int>
Keep this as `val`, if you want to assign a different like list to a news you can use `copy(...)`

2019-08-05 18:52 UTC, lmiotti commented on app/src/main/java/ar/com/wolox/android/example/ui/newdetail/NewDetailPresenter.kt
> +class NewDetailPresenter @Inject constructor(private val mRetrofitServices: RetrofitServices, private val mUserSession: UserSession, private val mApplication: Application) : BasePresenter<INewDetailV
Move parameters (retrofit and userSession) to new lines. Avoid too long lines. Moreover, remember to remove m as prefix.

2019-08-05 18:53 UTC, lmiotti requested changes
It's almost good, check the things I've mentioned and we're done

2019-08-06 20:03 UTC, lfmontesanto reviewed
good work. I left a small suggestion

2019-08-06 20:03 UTC, lfmontesanto commented on app/src/main/java/ar/com/wolox/android/example/ui/newdetail/NewDetailFragment.kt
> +        if (arguments != null) {
just a suggestion, you can make something like this here instead of the if (!null) :
`arguments.let {
    code that runs if arguments is not null } ?: run {
        code that runs if null
    }`

2019-08-06 20:03 UTC, lfmontesanto commented on app/src/main/java/ar/com/wolox/android/example/ui/newdetail/fullscreen/FullScreenPictureDialog.kt
> +
same as above

2019-08-07 14:32 UTC, lmiotti approved these changes
Congratulations! That was the last obligatory card of the PR. Now we are focusing on some extras until project arrives!

![minions](https://user-images.githubusercontent.com/36635668/62631346-94d98c80-b8fe-11e9-81cd-687e1bc2cb1c.gif)

2019-08-07 14:34 UTC, merged